updated to latest nightly build 0.8.22022102-3497

diff --git a/homegear/base/image-data/etc/cont-init.d/01-prepare-folders b/homegear/base/image-data/etc/cont-init.d/01-prepare-folders
--- a/homegear/base/image-data/etc/cont-init.d/01-prepare-folders
+++ b/homegear/base/image-data/etc/cont-init.d/01-prepare-folders
@@ -15,8 +15,8 @@ if ! [ "$(ls -A /config/homegear)" ]; then
 fi
 
 if [ ! -e /config/homegear/nodeBlueCredentialKey.txt ]; then
-	tr -dc A-Za-z0-9 < /dev/urandom | head -c 43 > /config/homegear/nodeBlueCredentialKey.txt
-	chmod 400 /config/homegear/nodeBlueCredentialKey.txt
+    tr -dc A-Za-z0-9 < /dev/urandom | head -c 43 > /config/homegear/nodeBlueCredentialKey.txt
+    chmod 400 /config/homegear/nodeBlueCredentialKey.txt
 fi
 
 if ! [ "$(ls -A /share/homegear/data)" ]; then
@@ -34,11 +34,11 @@ else
 
     rm -Rf /share/homegear/data/node-blue/node-red
     cp -a /var/lib/homegear.data/node-blue/node-red /share/homegear/data/node-blue/
-	  (( $? != 0 )) && echo "Could not copy nodes to \"homegear.data/node-blue/node-red\". Please check the permissions on this directory and make sure it is writeable."
+    (( $? != 0 )) && echo "Could not copy nodes to \"homegear.data/node-blue/node-red\". Please check the permissions on this directory and make sure it is writeable."
 
     rm -Rf /share/homegear/data/node-blue/www
     cp -a /var/lib/homegear.data/node-blue/www /share/homegear/data/node-blue/
-    (( $? != 0 )) && echo "Could not copy Node-BLUE frontend to \"homegear.data/node-blue/www\". Please check the permissions on this directory and make sure it is writeable." 
+    (( $? != 0 )) && echo "Could not copy Node-BLUE frontend to \"homegear.data/node-blue/www\". Please check the permissions on this directory and make sure it is writeable."
 
     mkdir -p /var/lib/homegear.data/admin-ui
     if ! cmp -s "/var/lib/homegear.data/admin-ui/.version" "/share/homegear/data/admin-ui/.version"; then
@@ -55,8 +55,8 @@ fi
 rm -f /share/homegear/data/homegear_updated
 
 # if [[ -d /share/homegear/data/node-blue/node-red ]]; then
-# 	  cd /share/homegear/data/node-blue/node-red
+#     cd /share/homegear/data/node-blue/node-red
 #     . "$NVM_DIR/nvm.sh"
 #     nvm alias default "${NODE_VERSION}"
-# 	  npm install --python=/usr/bin/python2.7
+#     npm install --python=/usr/bin/python2.7
 # fi
